"""Command-line interface for phabricator-review."""

import argparse
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional
from zoneinfo import ZoneInfo

from .config import get_config_path, load_config, load_dotenv_file, save_config
from .constants import (
    COLOR_ADD,
    COLOR_NOTICE,
    COLOR_REMOVE,
    COLOR_RESET,
    COLOR_SECTION,
    COLOR_TITLE,
    DEFAULT_MODEL,
    REVIEW_OUTPUT_DIR,
)
from .diff_parser import colorize, extract_code_snippet, summarize_diff
from .phabricator import PhabricatorClient, RevisionInfo
from .reviewer import CodeReviewer, ReviewResult


def format_review(review: ReviewResult, raw_diff: str = "", show_snippets: bool = True) -> str:
    """Format a review result for terminal output."""
    lines = []
    
    if review.summary:
        lines.append(colorize("Summary:", COLOR_SECTION))
        for item in review.summary:
            lines.append(f"- {item}")
        lines.append("")
    
    lines.append(colorize("Requested Changes:", COLOR_SECTION))
    if not review.requested_changes:
        lines.append("- None")
    else:
        for rc in review.requested_changes:
            line_str = str(rc.line) if rc.line else ""
            if line_str:
                lines.append(
                    f"- {colorize(rc.path, COLOR_TITLE)}:{colorize(line_str, COLOR_NOTICE)} - {rc.change}"
                )
            else:
                lines.append(f"- {colorize(rc.path, COLOR_TITLE)} - {rc.change}")
            
            # Add code snippet if available
            if show_snippets and raw_diff and rc.path and rc.line:
                snippet = extract_code_snippet(raw_diff, rc.path, rc.line)
                if snippet:
                    lines.append(colorize("  Code:", COLOR_NOTICE))
                    for snippet_line in snippet.split("\n"):
                        lines.append(f"    {snippet_line}")
    
    return "\n".join(lines)


def format_review_markdown(
    review: ReviewResult,
    revision: RevisionInfo,
    raw_diff: str,
    change_summary: str,
    model: str,
) -> str:
    """Format a review result as markdown for file output."""
    lines = []
    
    # IST timestamp
    ist = ZoneInfo("Asia/Kolkata")
    timestamp = datetime.now(ist).strftime("%d/%m/%Y %I:%M %p")
    
    # Header
    lines.append(f"Review generated on {timestamp}")
    lines.append(f"Review generated by - {model}")
    lines.append("")
    lines.append(f"# Review: D{revision.id} - {revision.title}")
    lines.append("")
    lines.append(f"**Status:** {revision.status}")
    lines.append(f"**URL:** {revision.uri}")
    lines.append("")
    
    # Revision summary
    if revision.summary:
        lines.append("## Description")
        lines.append("")
        lines.append(revision.summary)
        lines.append("")
    
    # LLM Review Summary
    lines.append("## Review Summary")
    lines.append("")
    if review.summary:
        for item in review.summary:
            lines.append(f"- {item}")
    else:
        lines.append("No summary provided.")
    lines.append("")
    
    # Requested Changes with code snippets
    lines.append("## Requested Changes")
    lines.append("")
    
    if not review.requested_changes:
        lines.append("✅ No issues found.")
    else:
        for i, rc in enumerate(review.requested_changes, 1):
            line_str = str(rc.line) if rc.line else ""
            if line_str:
                lines.append(f"### {i}. `{rc.path}` (line {line_str})")
            else:
                lines.append(f"### {i}. `{rc.path}`")
            lines.append("")
            lines.append(f"**Issue:** {rc.change}")
            lines.append("")
            
            # Add code snippet
            if raw_diff and rc.path and rc.line:
                snippet = extract_code_snippet(raw_diff, rc.path, rc.line, context_lines=2)
                if snippet:
                    # Detect language from file extension
                    ext = rc.path.split(".")[-1] if "." in rc.path else ""
                    lang_map = {
                        "py": "python",
                        "js": "javascript",
                        "html": "html",
                        "css": "css",
                        "less": "less",
                    }
                    lang = lang_map.get(ext, "")
                    lines.append(f"```{lang}")
                    lines.append(snippet)
                    lines.append("```")
                    lines.append("")
    
    # Change Summary
    if change_summary:
        lines.append("## Change Summary")
        lines.append("")
        # Remove ANSI color codes for markdown
        clean_summary = change_summary
        for code in [COLOR_ADD, COLOR_REMOVE, COLOR_NOTICE, COLOR_TITLE, COLOR_SECTION, COLOR_RESET]:
            clean_summary = clean_summary.replace(code, "")
        lines.append(clean_summary)
        lines.append("")
    
    return "\n".join(lines)


def save_review_markdown(
    review: ReviewResult,
    revision: RevisionInfo,
    raw_diff: str,
    change_summary: str,
    model: str,
) -> Path:
    """Save review to a markdown file."""
    output_dir = Path(REVIEW_OUTPUT_DIR)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    base_name = f"D{revision.id}"
    filename = f"{base_name}.md"
    filepath = output_dir / filename
    
    # Handle filename collision with incremental numbering
    counter = 1
    while filepath.exists():
        filename = f"{base_name}_{counter}.md"
        filepath = output_dir / filename
        counter += 1
    
    content = format_review_markdown(review, revision, raw_diff, change_summary, model)
    filepath.write_text(content)
    
    return filepath


def cmd_config(args: argparse.Namespace) -> int:
    """Handle the config command."""
    config_path = get_config_path()
    
    # Load existing config
    existing = {}
    if config_path.exists():
        existing = load_dotenv_file(config_path)
    
    # Get values from flags or prompt
    def get_value(flag_value: Optional[str], key: str, label: str) -> str:
        if flag_value:
            return flag_value.strip()
        
        current = existing.get(key, "")
        if current:
            prompt = f"{label} [{current}]: "
        else:
            prompt = f"{label}: "
        
        try:
            value = input(prompt).strip()
        except (EOFError, KeyboardInterrupt):
            print()
            return current
        
        return value if value else current
    
    phabricator_url = get_value(args.phabricator_url, "PHABRICATOR_URL", "Phabricator URL")
    if not phabricator_url:
        print(colorize("❌ Phabricator URL is required", COLOR_REMOVE), file=sys.stderr)
        return 1
    
    phabricator_token = get_value(
        args.phabricator_token, "PHABRICATOR_API_TOKEN", "Phabricator API Token"
    )
    if not phabricator_token:
        print(colorize("❌ Phabricator API Token is required", COLOR_REMOVE), file=sys.stderr)
        return 1
    
    openrouter_key = get_value(args.openrouter_key, "OPENROUTER_API_KEY", "OpenRouter API Key")
    if not openrouter_key:
        print(colorize("❌ OpenRouter API Key is required", COLOR_REMOVE), file=sys.stderr)
        return 1
    
    model = get_value(args.model, "REVIEW_MODEL", f"Model (default: {DEFAULT_MODEL})")
    
    saved_path = save_config(phabricator_url, phabricator_token, openrouter_key, model or None)
    print(colorize(f"✅ Configuration saved to {saved_path}", COLOR_ADD))
    
    return 0


def cmd_review(args: argparse.Namespace) -> int:
    """Handle the review command (default)."""
    try:
        config = load_config()
    except ValueError as e:
        print(colorize(f"❌ {e}", COLOR_REMOVE), file=sys.stderr)
        return 1
    
    revision_id = args.revision_id
    
    # Override model if specified via CLI
    model = getattr(args, "model", None) or config.model or DEFAULT_MODEL
    
    # Fetch revision and diff from Phabricator
    try:
        client = PhabricatorClient(config.phabricator_url, config.phabricator_api_token)
        revision, raw_diff = client.get_revision_diff(revision_id)
    except Exception as e:
        print(colorize(f"❌ Error fetching diff: {e}", COLOR_REMOVE), file=sys.stderr)
        return 1
    
    # Parse the diff
    changes, change_summary = summarize_diff(raw_diff)
    
    # Build full output
    output_lines = []
    output_lines.append(f"Revision D{revision.id}: {revision.title}")
    output_lines.append(f"Status: {revision.status}")
    output_lines.append(f"URL: {revision.uri}")
    
    if revision.summary:
        output_lines.append("")
        output_lines.append(colorize("--- Summary ---", COLOR_SECTION))
        output_lines.append(revision.summary)
    
    if change_summary:
        output_lines.append("")
        output_lines.append(colorize("--- Change Summary ---", COLOR_SECTION))
        output_lines.append(change_summary)
    
    if not args.only_review:
        output_lines.append("")
        output_lines.append(colorize("--- Raw Diff ---", COLOR_SECTION))
        output_lines.append(raw_diff)
    
    # Get LLM review
    review = None
    try:
        reviewer = CodeReviewer(config.openrouter_api_key, model)
        review = reviewer.review(raw_diff, change_summary, revision.summary)
        review_output = format_review(review, raw_diff, show_snippets=True)
    except Exception as e:
        review_output = f"Failed to generate review: {e}"
    
    output_lines.append("")
    output_lines.append(colorize("--- LLM Review ---", COLOR_SECTION))
    output_lines.append(review_output)
    
    # Handle --save-review flag
    save_review = getattr(args, "save_review", False)
    if save_review:
        if review:
            try:
                filepath = save_review_markdown(review, revision, raw_diff, change_summary, model)
                print(colorize(f"✅ Review saved to: {filepath}", COLOR_ADD))
            except Exception as e:
                print(colorize(f"❌ Failed to save review: {e}", COLOR_REMOVE), file=sys.stderr)
        else:
            print(colorize("❌ Failed to generate review content.", COLOR_REMOVE), file=sys.stderr)
            print(review_output)

    if args.only_review:
        # Only print the review section
        print(review_output)
    elif not save_review:
        print("\n".join(output_lines))
    
    return 0


def main() -> int:
    """Main entry point for the CLI."""
    # Check if first arg is 'config' to use subcommand mode
    if len(sys.argv) > 1 and sys.argv[1] == "config":
        parser = argparse.ArgumentParser(
            prog="phabreview config",
            description="Configure phabreview credentials",
        )
        parser.add_argument(
            "--phabricator-url",
            help="Phabricator Conduit base URL (e.g., https://phab.example.com/api/)",
        )
        parser.add_argument("--phabricator-token", help="Phabricator API token")
        parser.add_argument("--openrouter-key", help="OpenRouter API key")
        parser.add_argument("--model", help=f"LLM model to use (default: {DEFAULT_MODEL})")
        
        args = parser.parse_args(sys.argv[2:])
        return cmd_config(args)
    
    # Default: review mode
    parser = argparse.ArgumentParser(
        prog="phabreview",
        description="Review Phabricator revisions with LLM-powered code analysis",
        epilog="Use 'phabreview config' to configure credentials.",
    )
    parser.add_argument("revision_id", nargs="?", help="Revision ID to review (e.g., D12345)")
    parser.add_argument(
        "--only-review",
        action="store_true",
        help="Only print the LLM review section",
    )
    parser.add_argument(
        "--save-review",
        action="store_true",
        help="Save the review as a markdown file in ~/Documents/Phabreview/",
    )
    parser.add_argument(
        "--model",
        help=f"Override the LLM model for this review (default: {DEFAULT_MODEL})",
    )
    
    args = parser.parse_args()
    
    if args.revision_id:
        return cmd_review(args)
    else:
        parser.print_help()
        return 0


if __name__ == "__main__":
    sys.exit(main())
